// SQL Queries
// export const createTodoTableQuery = `
// CREATE TABLE IF NOT EXISTS todo (
//     ID SERIAL PRIMARY KEY,
//     name VARCHAR(255),
//     email VARCHAR(255),
//     phone VARCHAR(255),
//     university VARCHAR(255),
//     college VARCHAR(255),
//     course_duration VARCHAR(255),
//     course VARCHAR(255),
//     field_of_interest VARCHAR(255),
//     skills VARCHAR(255),
//     last_internship_details VARCHAR(255),
//     publications TEXT,
//     publicationslink VARCHAR(255),
//     Class10Education VARCHAR(255),
//     Class10_percentage VARCHAR(255),
//     Class10_year_of_passing VARCHAR(255),
//     Class12Education VARCHAR(255),
//     Class12_percentage VARCHAR(255),
//     Class12_year_of_passing VARCHAR(255),
//     graduation_university VARCHAR(255),
//     graduation_percentage VARCHAR(255),
//     graduation_year_of_passing VARCHAR(255),
//     masters_university VARCHAR(255),
//     masters_percentage VARCHAR(255),
//     masters_year_of_passing VARCHAR(255),
//     LastInternshipDetails VARCHAR(255),
//     HaveYouParticipatedinMootCourt VARCHAR(255),
//     PreferredLocation VARCHAR(255),
//     Answer1 TEXT,
//     Answer2 TEXT,
//     Answer3 TEXT,
//     UploadResume VARCHAR(255),
//     Answer1_PartA VARCHAR(255),
//     Answer2_PartA VARCHAR(255),
//     Answer3_PartA VARCHAR(255),
//     Answer4_PartA VARCHAR(255),
//     Answer5_PartA VARCHAR(255),
//     Answer6_PartA VARCHAR(255),
//     Answer7_PartA VARCHAR(255),
//     Answer8_PartA VARCHAR(255),
//     Answer9_PartA VARCHAR(255),
//     Answer10_PartA VARCHAR(255),
//     Answer11_PartA VARCHAR(255),
//     Answer12_PartA VARCHAR(255),
//     Answer13_PartA VARCHAR(255),
//     Answer14_PartA VARCHAR(255),
//     Answer1_PartB TEXT,
//     Answer2_PartB TEXT,
//     Answer3_PartB TEXT,
//     Answer1_PartC TEXT,
//     Answer2_PartC TEXT,
//     Answer3_PartC TEXT,
//     Answer1_PartD VARCHAR(255),
//     Answer2_PartD VARCHAR(255),
//     Answer3_PartD VARCHAR(255),
//     Answer4_PartD VARCHAR(255),
//     Answer5_PartD VARCHAR(255),
//     Answer6_PartD VARCHAR(255),
//     Answer7_PartD VARCHAR(255),
//     Answer8_PartD VARCHAR(255),
//     Answer9_PartD VARCHAR(255),
//     Answer10_PartD VARCHAR(255),
//     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
// );
// `;

export const createTodoTableQuery = `
CREATE TABLE IF NOT EXISTS todo (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    field_of_interest VARCHAR(255),
    linkedin_url VARCHAR(255),
    university VARCHAR(255),
    college VARCHAR(255),
    course_duration VARCHAR(255),
    course VARCHAR(255),
    publications TEXT,
    publications_link VARCHAR(255),
    class_10_education VARCHAR(255),
    class_10_percentage VARCHAR(255),
    class_10_year_of_passing VARCHAR(255),
    class_12_education VARCHAR(255),
    class_12_percentage VARCHAR(255),
    class_12_year_of_passing VARCHAR(255),
    masters_university VARCHAR(255),
    masters_percentage VARCHAR(255),
    masters_year_of_passing VARCHAR(255),
    last_internship_details VARCHAR(255),
    preferred_location VARCHAR(255),
    upload_resume VARCHAR(255),
    skills VARCHAR(255),
    aptitude_answer1 VARCHAR(255),
    aptitude_answer2 VARCHAR(255),
    aptitude_answer3 VARCHAR(255),
    aptitude_answer4 VARCHAR(255),
    aptitude_answer5 VARCHAR(255),
    aptitude_answer6 VARCHAR(255),
    aptitude_answer7 VARCHAR(255),
    aptitude_answer8 VARCHAR(255),
    aptitude_answer9 VARCHAR(255),
    aptitude_answer10 VARCHAR(255),
    answer1 TEXT,
    answer2 TEXT,
    answer3 TEXT,
    answer1_part_a VARCHAR(255),
    answer2_part_a VARCHAR(255),
    answer3_part_a VARCHAR(255),
    answer4_part_a VARCHAR(255),
    answer5_part_a VARCHAR(255),
    answer6_part_a VARCHAR(255),
    answer7_part_a VARCHAR(255),
    answer8_part_a VARCHAR(255),
    answer9_part_a VARCHAR(255),
    answer10_part_a VARCHAR(255),
    answer11_part_a VARCHAR(255),
    answer12_part_a VARCHAR(255),
    answer13_part_a VARCHAR(255),
    answer14_part_a VARCHAR(255),
    answer1_part_b TEXT,
    answer2_part_b TEXT,
    answer3_part_b TEXT,
    answer1_part_c TEXT,
    answer2_part_c TEXT,
    answer3_part_c TEXT,
    answer1_part_d VARCHAR(255),
    answer2_part_d VARCHAR(255),
    answer3_part_d VARCHAR(255),
    answer4_part_d VARCHAR(255),
    answer5_part_d VARCHAR(255),
    answer6_part_d VARCHAR(255),
    answer7_part_d VARCHAR(255),
    answer8_part_d VARCHAR(255),
    answer9_part_d VARCHAR(255),
    answer10_part_d VARCHAR(255),
    answer1_entertainment_and_media_law VARCHAR(255),
    answer2_entertainment_and_media_law VARCHAR(255),
    answer3_entertainment_and_media_law VARCHAR(255),
    answer1_capital_market_securities VARCHAR(255),
    answer1_banking_law VARCHAR(255),
    answer2_banking_law VARCHAR(255),
    answer3_banking_law VARCHAR(255),
    answer1_mediation_and_conciliation VARCHAR(255),
    answer2_mediation_and_conciliation VARCHAR(255),
    answer3_mediation_and_conciliation VARCHAR(255),
    answer1_merger_acquisition VARCHAR(255),
    answer2_merger_acquisition VARCHAR(255),
    answer3_merger_acquisition VARCHAR(255),
    answer1_sports_law VARCHAR(255),
    answer2_sports_law VARCHAR(255),
    answer3_sports_law VARCHAR(255),
    answer1_intellectual_property_rights VARCHAR(255),
    answer2_intellectual_property_rights VARCHAR(255),
    answer3_intellectual_property_rights VARCHAR(255),
    answer1_labour_laws VARCHAR(255),
    answer2_labour_laws VARCHAR(255),
    answer3_labour_laws VARCHAR(255),
    answer1_international_business_law VARCHAR(255),
    answer2_international_business_law VARCHAR(255),
    answer3_international_business_law VARCHAR(255),
    answer1_startup_in_india_related_legal_question VARCHAR(255),
    answer2_startup_in_india_related_legal_question VARCHAR(255),
    answer3_startup_in_india_related_legal_question VARCHAR(255),
    answer1_insurance_law VARCHAR(255),
    answer2_insurance_law VARCHAR(255),
    answer3_insurance_law VARCHAR(255),
    answer1_joint_venture_public_private_partnership_and_msme VARCHAR(255),
    answer2_joint_venture_public_private_partnership_and_msme VARCHAR(255),
    answer3_joint_venture_public_private_partnership_and_msme VARCHAR(255),
    answer1_tax_law VARCHAR(255),
    answer2_tax_law VARCHAR(255),
    answer3_tax_law VARCHAR(255),
    answer1_arbitration VARCHAR(255),
    answer2_arbitration VARCHAR(255),
    answer3_arbitration VARCHAR(255),
    answer4_arbitration VARCHAR(255),
    answer5_arbitration VARCHAR(255),
    answer1_ibc VARCHAR(255),
    answer2_ibc VARCHAR(255),
    answer3_ibc VARCHAR(255),
    answer1_competitive_and_anti_trust VARCHAR(255),
    answer1_aviation_law VARCHAR(255),
    answer2_aviation_law VARCHAR(255),
    answer3_aviation_law VARCHAR(255),
    answer4_aviation_law VARCHAR(255),
    answer1_environment VARCHAR(255),
    answer2_environment VARCHAR(255),
    answer3_environment VARCHAR(255),
    answer4_environment VARCHAR(255),
    answer5_environment VARCHAR(255),
    answer1_public_policy VARCHAR(255),
    answer2_public_policy VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`;

export const insertTodoQuery1 = `
UPDATE todo
SET
    name = $2,
    email = $3,
    phone = $4,
    field_of_interest = $5,
    linkedin_url = $6,
    university = $7,
    college = $8,
    course_duration = $9,
    course = $10,
    publications = $11,
    publications_link = $12,
    class_10_education = $13,
    class_10_percentage = $14,
    class_10_year_of_passing = $15,
    class_12_education = $16,
    class_12_percentage = $17,
    class_12_year_of_passing = $18,
    masters_university = $19,
    masters_percentage = $20,
    masters_year_of_passing = $21,
    last_internship_details = $22,
    preferred_location = $23,
    upload_resume = $24,
    skills = $25
WHERE
    id = $1
RETURNING *;
`;

export const updateTodoQuery = `
UPDATE todo
SET
    Aptitude_answer1 = $1,
    Aptitude_answer2 = $2,
    Aptitude_answer3 = $3,
    Aptitude_answer4 = $4,
    Aptitude_answer5 = $5,
    Aptitude_answer6 = $6,
    Aptitude_answer7 = $7,
    Aptitude_answer8 = $8,
    Aptitude_answer9 = $9,
    Aptitude_answer10 = $10
WHERE
    ID = $11
RETURNING *;
`;


export const insertTodoQuery3 = `
    UPDATE todo
    SET
        Answer1 = $1,
        Answer2 = $2,
        Answer3 = $3
    WHERE
        ID = $4
    RETURNING *;
`;

// Define the SQL query for inserting or updating all the fields
export const insertLastRoundDataQuery = `
    UPDATE todo
    SET
        Answer1_PartA = $1,
        Answer2_PartA = $2,
        Answer3_PartA = $3,
        Answer4_PartA = $4,
        Answer5_PartA = $5,
        Answer6_PartA = $6,
        Answer7_PartA = $7,
        Answer8_PartA = $8,
        Answer9_PartA = $9,
        Answer10_PartA = $10,
        Answer11_PartA = $11,
        Answer12_PartA = $12,
        Answer13_PartA = $13,
        Answer14_PartA = $14,
        Answer1_PartB = $15,
        Answer2_PartB = $16,
        Answer3_PartB = $17,
        Answer1_PartC = $18,
        Answer2_PartC = $19,
        Answer3_PartC = $20,
        Answer1_PartD = $21,
        Answer2_PartD = $22,
        Answer3_PartD = $23,
        Answer4_PartD = $24,
        Answer5_PartD = $25,
        Answer6_PartD = $26,
        Answer7_PartD = $27,
        Answer8_PartD = $28,
        Answer9_PartD = $29,
        Answer10_PartD = $30,
        Answer1_Entertainment_and_Media_Law = $31,
        Answer2_Entertainment_and_Media_Law = $32,
        Answer3_Entertainment_and_Media_Law = $33,
        Answer1_Capital_Market_Securities = $34,
        Answer1_Banking_Law = $35,
        Answer2_Banking_Law = $36,
        Answer3_Banking_Law = $37,
        Answer1_Mediation_and_Conciliation = $38,
        Answer2_Mediation_and_Conciliation = $39,
        Answer3_Mediation_and_Conciliation = $40,
        Answer1_Merger_Acquisition = $41,
        Answer2_Merger_Acquisition = $42,
        Answer3_Merger_Acquisition = $43,
        Answer1_Sports_Law = $44,
        Answer2_Sports_Law = $45,
        Answer3_Sports_Law = $46,
        Answer1_Intellectual_Property_Rights = $47,
        Answer2_Intellectual_Property_Rights = $48,
        Answer3_Intellectual_Property_Rights = $49,
        Answer1_Labour_Laws = $50,
        Answer2_Labour_Laws = $51,
        Answer3_Labour_Laws = $52,
        Answer1_International_Business_Law = $53,
        Answer2_International_Business_Law = $54,
        Answer3_International_Business_Law = $55,
        Answer1_Startup_in_India_related_legal_Question = $56,
        Answer2_Startup_in_India_related_legal_Question = $57,
        Answer3_Startup_in_India_related_legal_Question = $58,
        Answer1_Insurance_Law = $59,
        Answer2_Insurance_Law = $60,
        Answer3_Insurance_Law = $61,
        Answer1_Joint_Venture_Public_private_partnership_and_MSME = $62,
        Answer2_Joint_Venture_Public_private_partnership_and_MSME = $63,
        Answer3_Joint_Venture_Public_private_partnership_and_MSME = $64,
        Answer1_Tax_Law = $65,
        Answer2_Tax_Law = $66,
        Answer3_Tax_Law = $67,
        Answer1_ARBITRATION = $68,
        Answer2_ARBITRATION = $69,
        Answer3_ARBITRATION = $70,
        Answer4_ARBITRATION = $71,
        Answer5_ARBITRATION = $72,
        Answer1_IBC = $73,
        Answer2_IBC = $74,
        Answer3_IBC = $75,
        Answer1_Competitive_and_Anti_Trust = $76,
        Answer1_AVIATION_LAW = $77,
        Answer2_AVIATION_LAW = $78,
        Answer3_AVIATION_LAW = $79,
        Answer4_AVIATION_LAW = $80,
        Answer1_Environment = $81,
        Answer2_Environment = $82,
        Answer3_Environment = $83,
        Answer4_Environment = $84,
        Answer5_Environment = $85,
        Answer1_Public_Policy = $86,
        Answer2_Public_Policy = $87
    WHERE
        ID = $88
    RETURNING *;
`;


export const getAllTodoQuery = "SELECT * FROM todo";

export const getTodoByIdQuery = "SELECT * FROM todo WHERE id = $1;"

// SQL Query to delete a todo by ID
export const deleteTodoByIdQuery = "DELETE FROM todo WHERE id = $1";

