// SQL Queries
// export const createTodoTableQuery = `
// CREATE TABLE IF NOT EXISTS todo (
//     ID SERIAL PRIMARY KEY,
//     name VARCHAR(255),
//     email VARCHAR(255),
//     phone VARCHAR(255),
//     university VARCHAR(255),
//     college VARCHAR(255),
//     course_duration VARCHAR(255),
//     course VARCHAR(255),
//     field_of_interest VARCHAR(255),
//     skills VARCHAR(255),
//     last_internship_details VARCHAR(255),
//     publications TEXT,
//     publicationslink VARCHAR(255),
//     Class10Education VARCHAR(255),
//     Class10_percentage VARCHAR(255),
//     Class10_year_of_passing VARCHAR(255),
//     Class12Education VARCHAR(255),
//     Class12_percentage VARCHAR(255),
//     Class12_year_of_passing VARCHAR(255),
//     graduation_university VARCHAR(255),
//     graduation_percentage VARCHAR(255),
//     graduation_year_of_passing VARCHAR(255),
//     masters_university VARCHAR(255),
//     masters_percentage VARCHAR(255),
//     masters_year_of_passing VARCHAR(255),
//     LastInternshipDetails VARCHAR(255),
//     HaveYouParticipatedinMootCourt VARCHAR(255),
//     PreferredLocation VARCHAR(255),
//     Answer1 TEXT,
//     Answer2 TEXT,
//     Answer3 TEXT,
//     UploadResume VARCHAR(255),
//     Answer1_PartA VARCHAR(255),
//     Answer2_PartA VARCHAR(255),
//     Answer3_PartA VARCHAR(255),
//     Answer4_PartA VARCHAR(255),
//     Answer5_PartA VARCHAR(255),
//     Answer6_PartA VARCHAR(255),
//     Answer7_PartA VARCHAR(255),
//     Answer8_PartA VARCHAR(255),
//     Answer9_PartA VARCHAR(255),
//     Answer10_PartA VARCHAR(255),
//     Answer11_PartA VARCHAR(255),
//     Answer12_PartA VARCHAR(255),
//     Answer13_PartA VARCHAR(255),
//     Answer14_PartA VARCHAR(255),
//     Answer1_PartB TEXT,
//     Answer2_PartB TEXT,
//     Answer3_PartB TEXT,
//     Answer1_PartC TEXT,
//     Answer2_PartC TEXT,
//     Answer3_PartC TEXT,
//     Answer1_PartD VARCHAR(255),
//     Answer2_PartD VARCHAR(255),
//     Answer3_PartD VARCHAR(255),
//     Answer4_PartD VARCHAR(255),
//     Answer5_PartD VARCHAR(255),
//     Answer6_PartD VARCHAR(255),
//     Answer7_PartD VARCHAR(255),
//     Answer8_PartD VARCHAR(255),
//     Answer9_PartD VARCHAR(255),
//     Answer10_PartD VARCHAR(255),
//     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
// );
// `;

export const createTodoTableQuery = `
CREATE TABLE IF NOT EXISTS todo (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(255),
    field_of_interest VARCHAR(255),
    linkedin_url VARCHAR(255),
    university VARCHAR(255),
    college VARCHAR(255),
    course_duration VARCHAR(255),
    course VARCHAR(255),
    publications TEXT,
    publications_link VARCHAR(255),
    class_10_education VARCHAR(255),
    class_10_percentage VARCHAR(255),
    class_10_year_of_passing VARCHAR(255),
    class_12_education VARCHAR(255),
    class_12_percentage VARCHAR(255),
    class_12_year_of_passing VARCHAR(255),
    masters_university VARCHAR(255),
    masters_percentage VARCHAR(255),
    masters_year_of_passing VARCHAR(255),
    last_internship_details VARCHAR(255),
    preferred_location VARCHAR(255),
    upload_resume VARCHAR(255),
    skills VARCHAR(255),
    aptitude_answer1 VARCHAR(255),
    aptitude_answer2 VARCHAR(255),
    aptitude_answer3 VARCHAR(255),
    aptitude_answer4 VARCHAR(255),
    aptitude_answer5 VARCHAR(255),
    aptitude_answer6 VARCHAR(255),
    aptitude_answer7 VARCHAR(255),
    aptitude_answer8 VARCHAR(255),
    aptitude_answer9 VARCHAR(255),
    aptitude_answer10 VARCHAR(255),
    answer1 TEXT,
    answer2 TEXT,
    answer3 TEXT,
    answer1_part_a VARCHAR(255),
    answer2_part_a VARCHAR(255),
    answer3_part_a VARCHAR(255),
    answer4_part_a VARCHAR(255),
    answer5_part_a VARCHAR(255),
    answer6_part_a VARCHAR(255),
    answer7_part_a VARCHAR(255),
    answer8_part_a VARCHAR(255),
    answer9_part_a VARCHAR(255),
    answer10_part_a VARCHAR(255),
    answer11_part_a VARCHAR(255),
    answer12_part_a VARCHAR(255),
    answer13_part_a VARCHAR(255),
    answer14_part_a VARCHAR(255),
    answer1_part_b TEXT,
    answer2_part_b TEXT,
    answer3_part_b TEXT,
    answer1_part_c TEXT,
    answer2_part_c TEXT,
    answer3_part_c TEXT,
    answer1_part_d VARCHAR(255),
    answer2_part_d VARCHAR(255),
    answer3_part_d VARCHAR(255),
    answer4_part_d VARCHAR(255),
    answer5_part_d VARCHAR(255),
    answer6_part_d VARCHAR(255),
    answer7_part_d VARCHAR(255),
    answer8_part_d VARCHAR(255),
    answer9_part_d VARCHAR(255),
    answer10_part_d VARCHAR(255),
    answer1_entertainment_and_media_law VARCHAR(255),
    answer2_entertainment_and_media_law VARCHAR(255),
    answer3_entertainment_and_media_law VARCHAR(255),
    answer1_capital_market_securities VARCHAR(255),
    answer1_banking_law VARCHAR(255),
    answer2_banking_law VARCHAR(255),
    answer3_banking_law VARCHAR(255),
    answer1_mediation_and_conciliation VARCHAR(255),
    answer2_mediation_and_conciliation VARCHAR(255),
    answer3_mediation_and_conciliation VARCHAR(255),
    answer1_merger_acquisition VARCHAR(255),
    answer2_merger_acquisition VARCHAR(255),
    answer3_merger_acquisition VARCHAR(255),
    answer1_sports_law VARCHAR(255),
    answer2_sports_law VARCHAR(255),
    answer3_sports_law VARCHAR(255),
    answer1_intellectual_property_rights VARCHAR(255),
    answer2_intellectual_property_rights VARCHAR(255),
    answer3_intellectual_property_rights VARCHAR(255),
    answer1_labour_laws VARCHAR(255),
    answer2_labour_laws VARCHAR(255),
    answer3_labour_laws VARCHAR(255),
    answer1_international_business_law VARCHAR(255),
    answer2_international_business_law VARCHAR(255),
    answer3_international_business_law VARCHAR(255),
    answer1_startup_in_india_related_legal_question VARCHAR(255),
    answer2_startup_in_india_related_legal_question VARCHAR(255),
    answer3_startup_in_india_related_legal_question VARCHAR(255),
    answer1_insurance_law VARCHAR(255),
    answer2_insurance_law VARCHAR(255),
    answer3_insurance_law VARCHAR(255),
    answer1_joint_venture_public_private_partnership_and_msme VARCHAR(255),
    answer2_joint_venture_public_private_partnership_and_msme VARCHAR(255),
    answer3_joint_venture_public_private_partnership_and_msme VARCHAR(255),
    answer1_tax_law VARCHAR(255),
    answer2_tax_law VARCHAR(255),
    answer3_tax_law VARCHAR(255),
    answer1_arbitration VARCHAR(255),
    answer2_arbitration VARCHAR(255),
    answer3_arbitration VARCHAR(255),
    answer4_arbitration VARCHAR(255),
    answer5_arbitration VARCHAR(255),
    answer1_ibc VARCHAR(255),
    answer2_ibc VARCHAR(255),
    answer3_ibc VARCHAR(255),
    answer1_competitive_and_anti_trust VARCHAR(255),
    answer1_aviation_law VARCHAR(255),
    answer2_aviation_law VARCHAR(255),
    answer3_aviation_law VARCHAR(255),
    answer4_aviation_law VARCHAR(255),
    answer1_environment VARCHAR(255),
    answer2_environment VARCHAR(255),
    answer3_environment VARCHAR(255),
    answer4_environment VARCHAR(255),
    answer5_environment VARCHAR(255),
    answer1_public_policy VARCHAR(255),
    answer2_public_policy VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`;

export const insertTodoQuery1 = `
UPDATE todo
SET
    name = $2,
    email = $3,
    phone = $4,
    field_of_interest = $5,
    linkedin_url = $6,
    university = $7,
    college = $8,
    course_duration = $9,
    course = $10,
    publications = $11,
    publications_link = $12,
    class_10_education = $13,
    class_10_percentage = $14,
    class_10_year_of_passing = $15,
    class_12_education = $16,
    class_12_percentage = $17,
    class_12_year_of_passing = $18,
    masters_university = $19,
    masters_percentage = $20,
    masters_year_of_passing = $21,
    last_internship_details = $22,
    preferred_location = $23,
    upload_resume = $24,
    skills = $25
WHERE
    id = $1
RETURNING *;
`;

export const updateTodoQuery = `
UPDATE todo
SET
    Aptitude_answer1 = $1,
    Aptitude_answer2 = $2,
    Aptitude_answer3 = $3,
    Aptitude_answer4 = $4,
    Aptitude_answer5 = $5,
    Aptitude_answer6 = $6,
    Aptitude_answer7 = $7,
    Aptitude_answer8 = $8,
    Aptitude_answer9 = $9,
    Aptitude_answer10 = $10
WHERE
    ID = $11
RETURNING *;
`;


export const insertTodoQuery3 = `
    UPDATE todo
    SET
        Answer1 = $1,
        Answer2 = $2,
        Answer3 = $3
    WHERE
        ID = $4
    RETURNING *;
`;

// Define the SQL query for inserting or updating all the fields
export const insertLastRoundDataQuery = `
    UPDATE todo
    SET
        answer1_part_a = $1,
        answer2_part_a = $2,
        answer3_part_a = $3,
        answer4_part_a = $4,
        answer5_part_a = $5,
        answer6_part_a = $6,
        answer7_part_a = $7,
        answer8_part_a = $8,
        answer9_part_a = $9,
        answer10_part_a = $10,
        answer11_part_a = $11,
        answer12_part_a = $12,
        answer13_part_a = $13,
        answer14_part_a = $14,
        answer1_part_b = $15,
        answer2_part_b = $16,
        answer3_part_b = $17,
        answer1_part_c = $18,
        answer2_part_c = $19,
        answer3_part_c = $20,
        answer1_part_d = $21,
        answer2_part_d = $22,
        answer3_part_d = $23,
        answer4_part_d = $24,
        answer5_part_d = $25,
        answer6_part_d = $26,
        answer7_part_d = $27,
        answer8_part_d = $28,
        answer9_part_d = $29,
        answer10_part_d = $30,
        answer1_entertainment_and_media_law = $31,
        answer2_entertainment_and_media_law = $32,
        answer3_entertainment_and_media_law = $33,
        answer1_capital_market_securities = $34,
        answer1_banking_law = $35,
        answer2_banking_law = $36,
        answer3_banking_law = $37,
        answer1_mediation_and_conciliation = $38,
        answer2_mediation_and_conciliation = $39,
        answer3_mediation_and_conciliation = $40,
        answer1_merger_acquisition = $41,
        answer2_merger_acquisition = $42,
        answer3_merger_acquisition = $43,
        answer1_sports_law = $44,
        answer2_sports_law = $45,
        answer3_sports_law = $46,
        answer1_intellectual_property_rights = $47,
        answer2_intellectual_property_rights = $48,
        answer3_intellectual_property_rights = $49,
        answer1_labour_laws = $50,
        answer2_labour_laws = $51,
        answer3_labour_laws = $52,
        answer1_international_business_law = $53,
        answer2_international_business_law = $54,
        answer3_international_business_law = $55,
        answer1_startup_in_india_related_legal_question = $56,
        answer2_startup_in_india_related_legal_question = $57,
        answer3_startup_in_india_related_legal_question = $58,
        answer1_insurance_law = $59,
        answer2_insurance_law = $60,
        answer3_insurance_law = $61,
        answer1_joint_venture_public_private_partnership_and_msme = $62,
        answer2_joint_venture_public_private_partnership_and_msme = $63,
        answer3_joint_venture_public_private_partnership_and_msme = $64,
        answer1_tax_law = $65,
        answer2_tax_law = $66,
        answer3_tax_law = $67,
        answer1_arbitration = $68,
        answer2_arbitration = $69,
        answer3_arbitration = $70,
        answer4_arbitration = $71,
        answer5_arbitration = $72,
        answer1_ibc = $73,
        answer2_ibc = $74,
        answer3_ibc = $75,
        answer1_competitive_and_anti_trust = $76,
        answer1_aviation_law = $77,
        answer2_aviation_law = $78,
        answer3_aviation_law = $79,
        answer4_aviation_law = $80,
        answer1_environment = $81,
        answer2_environment = $82,
        answer3_environment = $83,
        answer4_environment = $84,
        answer5_environment = $85,
        answer1_public_policy = $86,
        answer2_public_policy = $87
    WHERE
        ID = $88
    RETURNING *;
`;



export const getAllTodoQuery = "SELECT * FROM todo";

export const getTodoByIdQuery = "SELECT * FROM todo WHERE id = $1;"

// SQL Query to delete a todo by ID
export const deleteTodoByIdQuery = "DELETE FROM todo WHERE id = $1";

